/**
    Nefertumm and Stevej
    https://github.com/Nefertumm/
    https://github.com/pangolp
 */

enum NpcPromotionGossip
{
    GOSSIP_MENU_PROMOTION = 62000,
    GOSSIP_MENU_WARRIOR_TANK = 0,
    GOSSIP_MENU_WARRIOR_DPS,
    GOSSIP_MENU_PALADIN_TANK,
    GOSSIP_MENU_PALADIN_HEAL,
    GOSSIP_MENU_PALADIN_DPS,
    GOSSIP_MENU_HUNTER,
    GOSSIP_MENU_ROGUE,
    GOSSIP_MENU_PRIEST_HEAL,
    GOSSIP_MENU_PRIEST_DPS,
    GOSSIP_MENU_DEATH_KNIGHT_TANK,
    GOSSIP_MENU_DEATH_KNIGHT_DPS,
    GOSSIP_MENU_SHAMAN_CASTER,
    GOSSIP_MENU_SHAMAN_MELEE,
    GOSSIP_MENU_SHAMAN_HEAL,
    GOSSIP_MENU_MAGE,
    GOSSIP_MENU_WARLOCK,
    GOSSIP_MENU_DRUID_TANK,
    GOSSIP_MENU_DRUID_HEAL,
    GOSSIP_MENU_DRUID_CASTER,
    GOSSIP_MENU_DRUID_MELEE,
    GOSSIP_MENU_CLOSE,
    GOSSIP_MENU_TP_DALARAN
};

enum NpcPromotionQuest
{
    QUEST_WHERE_KINGS_WALK = 13188,
    QUEST_WARCHIEFS_BLESSING = 13189
};

enum NpcTextId
{
    NPC_TEXT_ID = 90000
};

enum RidingSkills
{
    SKILL_RIDING_75 = 33388, // Rinding 75
    SKILL_RIDING_100 = 33391, // Rinding 100
    SKILL_RIDING_FLYING = 34090,
    SKILL_RIDING_ARTISING = 34091,
};

enum WeaponsSkills
{
    BLOCK = 107,
    BOWS = 264,
    CROSSBOWS = 5011,
    DAGGERS = 1180,
    FIST_WEAPONS = 15590,
    GUNS = 266,
    ONE_H_AXES = 196,
    ONE_H_MACES = 198,
    ONE_H_SWORDS = 201,
    POLEARMS = 200,
    SHOOT = 5019,
    STAVES = 227,
    TWO_H_AXES = 197,
    TWO_H_MACES = 199,
    TWO_H_SWORDS = 202,
    WANDS = 5009,
    THROW_WAR = 2567
};

enum NpcSpellsPlateMail
{
    PLATE_MAIL = 750,
    MAIL = 8737
};

enum NpcPromotionHunter
{
    AMMUNITION_ARROW = 41586,
    AMMUNITION_BULLETS = 41584,
    AMMUNITION_COUNT = 200
};
