/**
    Nefertumm and Stevej
    https://github.com/Nefertumm/
    https://github.com/pangolp
 */

enum NpcPromotionGossip
{
    GOSSIP_MENU_PROMOTION = 62000,
    GOSSIP_MENU_WARRIOR_TANK = 0,
    GOSSIP_MENU_WARRIOR_DPS = 1,
    GOSSIP_MENU_PALADIN_TANK = 2,
    GOSSIP_MENU_PALADIN_HEAL = 3,
    GOSSIP_MENU_PALADIN_DPS = 4,
    GOSSIP_MENU_HUNTER = 5,
    GOSSIP_MENU_ROGUE = 6,
    GOSSIP_MENU_PRIEST_HEAL = 7,
    GOSSIP_MENU_DEATH_KNIGHT_TANK = 8,
    GOSSIP_MENU_DEATH_KNIGHT_DPS = 9,
    GOSSIP_MENU_PRIEST_DPS = 10,
    GOSSIP_MENU_SHAMAN_CASTER = 11,
    GOSSIP_MENU_SHAMAN_MELEE = 12,
    GOSSIP_MENU_MAGE = 13,
    GOSSIP_MENU_WARLOCK = 14,
    GOSSIP_MENU_DRUID_TANK = 15,
    GOSSIP_MENU_DRUID_HEAL = 16,
    GOSSIP_MENU_DRUID_CASTER = 17,
    GOSSIP_MENU_DRUID_MELEE = 18,
    GOSSIP_MENU_CLOSE = 19,
    GOSSIP_MENU_TP_DALARAN = 20
};

enum NpcPromotionQuest
{
    QUEST_WHERE_KINGS_WALK = 13188,
    QUEST_WARCHIEFS_BLESSING = 13189
};

enum NpcTextId
{
    NPC_TEXT_ID = 90000
};

enum NpcItem
{
    EQUIPMENT_SLOT_WARRIOR_TANK_HEAD = 41350,
    EQUIPMENT_SLOT_WARRIOR_TANK_NECK = 45812,
    EQUIPMENT_SLOT_WARRIOR_TANK_SHOULDERS = 41351,
    EQUIPMENT_SLOT_WARRIOR_TANK_CHEST = 41353,
    EQUIPMENT_SLOT_WARRIOR_TANK_WAIST = 41352,
    EQUIPMENT_SLOT_WARRIOR_TANK_LEGS = 41347,
    EQUIPMENT_SLOT_WARRIOR_TANK_FEET = 41348,
    EQUIPMENT_SLOT_WARRIOR_TANK_WRISTS = 41354,
    EQUIPMENT_SLOT_WARRIOR_TANK_HANDS = 41349,
    EQUIPMENT_SLOT_WARRIOR_TANK_FINGER1 = 45809,
    EQUIPMENT_SLOT_WARRIOR_TANK_FINGER2 = 45809,
    EQUIPMENT_SLOT_WARRIOR_TANK_TRINKET1 = 36993,
    EQUIPMENT_SLOT_WARRIOR_TANK_TRINKET2 = 38359,
    EQUIPMENT_SLOT_WARRIOR_TANK_BACK = 45811,
    EQUIPMENT_SLOT_WARRIOR_TANK_MAINHAND = 36984,
    EQUIPMENT_SLOT_WARRIOR_TANK_OFFHAND = 37107,
    EQUIPMENT_SLOT_WARRIOR_TANK_RANGED = 36981
};

enum NpcSpells
{
    PLATE_MAIL = 750,
    MAIL = 8737
};
